### ISSUE TITLE
ogcapi-types release

### ISSUE THREAD

**Issue by pka** [georust/ogcapi#19]
tile-grid has a [branch](https://github.com/pka/tile-grid/tree/ogcapi-types) using ogcapi-types, which would require a release for merging. Let me know, if I can help.

**Comment by b4l** [comment]
@pka I created #20 which was something I wanted to do for a long time and finally found enough incentive. I hope this will serve you as well.

Also maybe some of the admins can add you to the `ogcapi-publishers` group so you can release at your own will.

**Comment by b4l** [comment]
Release v0.2.0 has been published to crates.io.

**Comment by pka** [comment]
Thanks a lot!
